### ISSUE TITLE
麻烦帮忙看一下点击所有按钮都报错

### ISSUE THREAD

**Issue by worldhe** [WZTENG/YOLOv5_NCNN#20]
dlopen failed empty/missing DT_HASH in "/data/app/com.wzt.yolov5-1/lib/arm64/libyolov5.so"（build with -hash-style=gnu?）

**Comment by WZTENG** [comment]
尝试下这个:
https://blog.csdn.net/keial/article/details/94748526

**Comment by worldhe** [comment]
> 尝试下这个:
> https://blog.csdn.net/keial/article/details/94748526

这个方法也没什么作用，我用了两个版本的手机Android5.0和Android7.1，下面是所有的报错信息：
`09-25 09:21:58.789 1981-1981/com.wzt.yolov5 E/art: dlopen("/data/app/com.wzt.yolov5-1/lib/arm64/libyolov5.so", RTLD_LAZY) failed: dlopen failed: empty/missing DT_HASH in "/data/app/com.wzt.yolov5-1/lib/arm64/libyolov5.so" (built with --hash-style=gnu?)
09-25 09:21:58.789 1981-1981/com.wzt.yolov5 D/AndroidRuntime: Shutting down VM
09-25 09:21:58.800 1981-1981/com.wzt.yolov5 E/Recovery: CrashData{crashCount=1, crashTime=1600996918799, shouldRestart=false}
09-25 09:21:58.806 1981-1981/com.wzt.yolov5 E/wzt: exceptionMessage:java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "/data/app/com.wzt.yolov5-1/lib/arm64/libyolov5.so" (built with --hash-style=gnu?)
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:989)
        at com.wzt.yolov5.YOLOv5.<clinit>(YOLOv5.java:8)
        at com.wzt.yolov5.MainActivity.onCreate(MainActivity.java:114)
        at android.app.Activity.performCreate(Activity.java:6074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2712)
        at android.app.ActivityThread.access$800(ActivityThread.java:185)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:5819)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:998)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
09-25 09:21:58.807 1981-1981/com.wzt.yolov5 E/wzt: cause:dlopen failed: empty/missing DT_HASH in "/data/app/com.wzt.yolov5-1/lib/arm64/libyolov5.so" (built with --hash-style=gnu?)
09-25 09:21:58.807 1981-1981/com.wzt.yolov5 E/wzt: exceptionClassName:java.lang.UnsatisfiedLinkError
09-25 09:21:58.807 1981-1981/com.wzt.yolov5 E/wzt: throwClassName:java.lang.Runtime
09-25 09:21:58.807 1981-1981/com.wzt.yolov5 E/wzt: throwMethodName:loadLibrary
09-25 09:21:58.807 1981-1981/com.wzt.yolov5 E/wzt: throwLineNumber:371
09-25 09:21:58.808 1981-1981/com.wzt.yolov5 W/System.err: java.lang.IllegalAccessException: Cannot access method: void com.android.internal.os.RuntimeInit$UncaughtHandler.<init>()
09-25 09:21:58.808 1981-1981/com.wzt.yolov5 W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
09-25 09:21:58.808 1981-1981/com.wzt.yolov5 W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
09-25 09:21:58.809 1981-1981/com.wzt.yolov5 W/System.err:     at com.zxy.recovery.tools.DefaultHandlerUtil.getDefaultUncaughtExceptionHandler(DefaultHandlerUtil.java:26)
09-25 09:21:58.809 1981-1981/com.wzt.yolov5 W/System.err:     at com.zxy.recovery.tools.DefaultHandlerUtil.isSystemDefaultUncaughtExceptionHandler(DefaultHandlerUtil.java:37)
09-25 09:21:58.809 1981-1981/com.wzt.yolov5 W/System.err:     at com.zxy.recovery.core.RecoveryHandler.uncaughtException(RecoveryHandler.java:99)
09-25 09:21:58.809 1981-1981/com.wzt.yolov5 W/System.err:     at com.wzt.yolov5.AppCrashHandler.uncaughtException(AppCrashHandler.java:11)
09-25 09:21:58.809 1981-1981/com.wzt.yolov5 W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
09-25 09:21:58.809 1981-1981/com.wzt.yolov5 W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
09-25 09:21:58.866 1981-1981/com.wzt.yolov5 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wzt.yolov5, PID: 1981
    java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "/data/app/com.wzt.yolov5-1/lib/arm64/libyolov5.so" (built with --hash-style=gnu?)
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:989)
        at com.wzt.yolov5.YOLOv5.<clinit>(YOLOv5.java:8)
        at com.wzt.yolov5.MainActivity.onCreate(MainActivity.java:114)
        at android.app.Activity.performCreate(Activity.java:6074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2712)
        at android.app.ActivityThread.access$800(ActivityThread.java:185)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:5819)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:998)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
09-25 09:21:58.973 1981-1981/com.wzt.yolov5 I/Process: Sending signal. PID: 1981 SIG: 9`

**Comment by WZTENG** [comment]
建议使用8.0及以上版本，ncnn最低7.0，但我的工程使用了新的功能需要8.0（8.0有些手机可以），9.0肯定没问题。

**Comment by worldhe** [comment]
> 建议使用8.0及以上版本，ncnn最低7.0，但我的工程使用了新的功能需要8.0（8.0有些手机可以），9.0肯定没问题。

ok谢谢，我先用虚拟器试一下，稍后回复您。

**Comment by WZTENG** [comment]
虚拟机可能需要自己填坑，没用过虚拟机。

**Comment by worldhe** [comment]
> 虚拟机可能需要自己填坑，没用过虚拟机。

谢谢，已经跑起来了，跟Android版本有关。换了一个魅族的Android7.1的手机，就可以跑了。
